<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.test.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.test.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Simple.MsTest.Sdk" Version="0.2.0-alpha.54" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="5.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="5.0.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.3" />
    <PackageReference Include="coverlet.collector" Version="3.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCore.Simple.Sdk.Api\AspNetCore.Simple.Sdk.Api.csproj" />
    <ProjectReference Include="..\AspNetCore.Simple.Sdk\AspNetCore.Simple.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Autoregistration\AppSettings\Json\appsettings.test.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
