# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master  
  - dev/*
  - feat/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  GitVersion.SemVer: ''

steps:

- task: UseDotNet@2
  displayName: Use .NET 5
  inputs:
    version: 5.0.x
    packageType: sdk
    includePreviewVersions: true

- task: gitversion/setup@0
  inputs:
    versionSpec: '5.6.0'    

- task: gitversion/execute@0
  inputs:
    useConfigFile: true
    configFilePath: "./GitVersion.yml"
    updateAssemblyInfoFilename: '**/AssemblyInfo.cs'
    updateAssemblyInfo: true
    
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'
    projects: './src/AspNetCore.Simple.Sdk.sln'
    configuration: '$(buildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: 'test'
    projects: './src/AspNetCore.Simple.Sdk.sln'
    arguments: '--configuration $(buildConfiguration)'
    versioningScheme: byEnvVar
    versionEnvVar: 'GitVersion.SemVer'

- task: DotNetCoreCLI@2
  displayName: pack
  inputs:
    command: 'pack'
    packagesToPack: './src/AspNetCore.Simple.Sdk/AspNetCore.Simple.Sdk.csproj'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'