<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <Nullable>enable</Nullable>
        <PackageLicenseFile>License.txt</PackageLicenseFile>
        <Authors>Rene Peuser</Authors>
        <Company>Rene Peuser Softwaresolutions</Company>
        <Description>
This simple SDK contains following helpful optimizations:
- ApiVersioning
- Errorhandling with middleware
- Logging with middleware
- Query security filter
- Optimized and simplified swagger.
- Ready to go base class for startup.cs</Description>
        <Copyright>Copyright 2021 (c) Rene Peuser. All rights reserved.</Copyright>
        <PackageProjectUrl>https://renepeuser.visualstudio.com/AspNetCore.Simple.Sdk</PackageProjectUrl>
        <RepositoryUrl>https://renepeuser.visualstudio.com/AspNetCore.Simple.Sdk</RepositoryUrl>
        <PackageReleaseNotes>Add Backoff service for retry timeout algorhytm</PackageReleaseNotes>
        <PackageTags>C#;.NetCore;Asp.NetCore;NetCore;ASPNetCore;Swagger;Swashbuckle;OpenAPI;ErrorHandling;ErrorLogging;Middleware;Startup.cs;</PackageTags>
        <PackageId>AspNetCore.Simple.Sdk</PackageId>
        <OutputType>Library</OutputType>
        <AssemblyName>AspNetCore.Simple.Sdk</AssemblyName>
        <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    </PropertyGroup>

    <!--Property group settings for source link !-->
    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <DebugType>embedded</DebugType>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <DocumentationFile>.\AspNetCore.Simple.Sdk.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Argument.Check" Version="2.0.0" />
        <PackageReference Include="Extensions.Pack" Version="2.0.0" />
        <PackageReference Include="GitVersion.MsBuild" Version="5.10.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MediatR" Version="10.0.1" />
        <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
        <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="1.1.1" PrivateAssets="All" />
        <PackageReference Include="StackExchange.Redis" Version="2.6.48" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.4.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.4.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUi" Version="6.4.0" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.21.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\License.txt">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

</Project>
