<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageLicenseFile>License.txt</PackageLicenseFile>
        <Authors>Rene Peuser</Authors>
        <Company>Rene Peuser Softwaresolutions</Company>
        <Description>
            This simple SDK contains following helpful optimizations:
            - ApiVersioning
            - Errorhandling with middleware
            - Logging with middleware
            - Query security filter
            - Optimized and simplified swagger.
            - Ready to go base class for startup.cs
        </Description>
        <Copyright>Copyright 2021 (c) Rene Peuser. All rights reserved.</Copyright>
        <PackageProjectUrl>https://renepeuser.visualstudio.com/AspNetCore.Simple.Sdk</PackageProjectUrl>
        <RepositoryUrl>https://renepeuser.visualstudio.com/AspNetCore.Simple.Sdk</RepositoryUrl>
        <PackageReleaseNotes>Update nuget packages</PackageReleaseNotes>
        <PackageTags>C#;.NetCore;Asp.NetCore;NetCore;ASPNetCore;Swagger;Swashbuckle;OpenAPI;ErrorHandling;ErrorLogging;Middleware;Startup.cs;</PackageTags>
        <PackageId>AspNetCore.Simple.Sdk</PackageId>
        <OutputType>Library</OutputType>
        <AssemblyName>AspNetCore.Simple.Sdk</AssemblyName>
        <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <OpenApiDocumentsDirectory>./</OpenApiDocumentsDirectory>
    </PropertyGroup>

    <!--Property group settings for source link !-->
    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
        <PackageReference Include="Extensions.Pack" Version="6.0.9" />
        <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MediatR" Version="12.5.0" />
        <PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
        <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
        <PackageReference Include="Microsoft.OpenApi.Readers" Version="1.6.28" />
        <PackageReference Include="Microsoft.SourceLink.AzureRepos.Git" Version="8.0.0" PrivateAssets="All" />
        <PackageReference Include="Polly" Version="8.6.4" />
        <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="9.0.6" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="9.0.6" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.6" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUi" Version="9.0.6" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\License.txt">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
        <None Include="..\..\readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
