<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AspNetCore.Simple.Sdk.Api</RootNamespace>
      <NoWarn>IDE0305</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>.\AspNetCore.Simple.Sdk.Api.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCore.Simple.Sdk\AspNetCore.Simple.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="AspNetCore.Simple.Sdk.Api.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
